export type Product = {
  id: string;
  slug: string;
  categorySlug: string;
  categoryName: string;
  name: string;
  description: string;
  features: string[];
  packaging: string;
  image?: string;
  whatIsIt?: string;
  whyUsed?: string;
};

export const productCategories = [
  {
    icon: "Boxes",
    title: "Laboratuvar Sarf Malzemeleri",
    description: "Günlük laboratuvar çalışmalarınız için plastik pipet uçları, tüpler ve borosilikat cam laboratuvar malzemeleri.",
    href: "/urunler/kategori/laboratuvar-sarf-malzemeleri",
    slug: "laboratuvar-sarf-malzemeleri",
    image: "/images/beher.jpeg",
  },
  {
    icon: "TestTube",
    title: "PCR Kitleri",
    description: "Genetik analizler, nükleik asit ekstraksiyon kitleri, master mixler ve moleküler biyoloji çözümleri.",
    href: "/urunler/kategori/pcr-kitleri",
    slug: "pcr-kitleri",
    image: "/images/pipet ucu- steril.jpeg",
  },
  {
    icon: "FlaskConical",
    title: "Kimyasallar ve Reaktifler",
    description: "Analitik testleriniz ve moleküler biyoloji çalışmalarınız için saf kimyasallar, tampon çözeltiler ve besiyerleri.",
    href: "/urunler/kategori/kimyasallar-ve-reaktifler",
    slug: "kimyasallar-ve-reaktifler",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    icon: "Cpu",
    title: "Laboratuvar Cihazları",
    description: "Yüksek teknolojiye sahip mekanik pipetler, santrifüjler, termal siklerler ve karıştırma sistemleri.",
    href: "/urunler/kategori/laboratuvar-cihazlari",
    slug: "laboratuvar-cihazlari",
    image: "/images/balon joje.jpeg",
  },
];

export const products: Product[] = [
  // --- 1. LABORATUVAR SARF MALZEMELERİ (PLASTİK VE CAM ÜRÜNLER) ---
  {
    id: "sarf-fipet-2-5",
    slug: "filtreli-pipet-ucu-2-5-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 0.1–2.5 µl",
    description: "Hassas moleküler biyoloji çalışmaları için aerosol kontaminasyonunu önleyen filtreli steril pipet ucu.",
    features: ["0.1–2.5 µl hacim aralığı", "DNaz, RNaz ve Pyrogen içermez", "Düşük tutunma özelliği"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
    whatIsIt: "Çok küçük hacimli sıvı aktarımlarında çapraz bulaşmayı önleyen filtreli uç.",
    whyUsed: "Hassas moleküler analizlerde aerosol bariyeri oluşturmak için kullanılır.",
  },
  {
    id: "sarf-fipet-10",
    slug: "filtreli-pipet-ucu-10-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 0.5–10 µl",
    description: "PCR ve genetik çalışmalar için kontaminasyonu önleyici racked steril filtreli pipet ucu.",
    features: ["0.5–10 µl hacim aralığı", "Steril ve saf polipropilen yapı"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-fipet-20",
    slug: "filtreli-pipet-ucu-20-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 2–20 µl",
    description: "Hassas sıvı transferleri için özel tasarlanmış filtreli steril pipet ucu.",
    features: ["2–20 µl hacim aralığı", "Yüksek şeffaflık"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-fipet-50",
    slug: "filtreli-pipet-ucu-50-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 5–50 µl",
    description: "Optimum akışkanlık ve sızdırmazlık sağlayan laboratuvar sarf malzemesi.",
    features: ["5–50 µl hacim aralığı", "DNaz/RNaz free"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-fipet-100",
    slug: "filtreli-pipet-ucu-100-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 10–100 µl",
    description: "Biyoteknolojik uygulamalar ve rutin testler için yüksek kaliteli filtreli uç.",
    features: ["10–100 µl hacim aralığı", "Otokotlanabilir rack ambalaj"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-fipet-200",
    slug: "filtreli-pipet-ucu-200-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 20–200 µl",
    description: "Standart mikropipetlerle tam uyumlu, sıvı kalıntısını en aza indiren filtreli uç.",
    features: ["20–200 µl hacim aralığı", "Düşük tutunma yüzeyi"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-fipet-1000",
    slug: "filtreli-pipet-ucu-1000-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Filtreli Pipet Ucu (Steril, DNaz/RNaz Free) - 100–1000 µl",
    description: "Büyük hacimli transferlerde aerosol kaçışını engelleyen uzun tip filtreli uç.",
    features: ["100–1000 µl hacim aralığı", "Steril"],
    packaging: "96 adet/rack",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-std-10",
    slug: "standart-pipet-ucu-10-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Pipet Ucu - 10 µl (Şeffaf / Sarı)",
    description: "Genel laboratuvar sıvı transferleri için ekonomik ve güvenilir standart pipet ucu.",
    features: ["10 µl kapasite", "Şeffaf/Sarı renk seçenekleri"],
    packaging: "1000 adet/paket",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-std-200",
    slug: "standart-pipet-ucu-200-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Pipet Ucu - 200 µl (Sarı)",
    description: "Yüksek uyumluluğa sahip standart sarf mikropipet ucu.",
    features: ["200 µl kapasite", "Esnek ve dayanıklı polipropilen"],
    packaging: "1000 adet/paket",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-std-1000",
    slug: "standart-pipet-ucu-1000-ul",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Pipet Ucu - 1000 µl (Mavi)",
    description: "Geniş hacimli günlük laboratuvar transferleri için mavi tip standart pipet ucu.",
    features: ["1000 µl kapasite", "Mavi renk kodlu"],
    packaging: "1000 adet/paket",
    image: "/images/products/pipet ucu- steril.jpeg",
  },
  {
    id: "sarf-falcon-15",
    slug: "santrifuj-falconi-tupleri-15ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Santrifüj Tüpü - 15 ml (Steril / Dereceli)",
    description: "Konik dipli, vidalı kapaklı yüksek hız dayanımlı santrifüj tüpü.",
    features: ["15 ml hacim", "Net derecelendirme çizgileri ve yazı alanı"],
    packaging: "50'li poşet",
    image: "/images/products/falkon tüp- 50 ml.jpeg",
  },
  {
    id: "sarf-falcon-50",
    slug: "santrifuj-falconi-tupleri-50ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Santrifüj Tüpü - 50 ml (Steril / Dereceli)",
    description: "Numune toplama ve saklama için yüksek dayanımlı steril falcon tüpü.",
    features: ["50 ml hacim", "Sızdırmaz kapak mekanizması"],
    packaging: "50'li poşet",
    image: "/images/products/falkon tüp- 50 ml.jpeg",
  },
  {
    id: "sarf-epp-1-5",
    slug: "mikrosantrifuj-tupu-1-5ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Mikrosantrifüj Tüpü - 1.5 ml (Kilitli Kapak)",
    description: "Ekstraksiyon ve saklama süreçleri için güvenli kilitli kapaklı eppendorf tüpü.",
    features: ["1.5 ml hacim", "Otokotlanabilir saf polipropilen"],
    packaging: "500 adet/paket",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "sarf-epp-2-0",
    slug: "mikrosantrifuj-tupu-2-0ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Mikrosantrifüj Tüpü - 2.0 ml (Kilitli Kapak)",
    description: "Daha yüksek hacimli örnek saklama işlemleri için kilitli kapaklı mikrotüp.",
    features: ["2.0 ml hacim", "Sızdırmaz kapak"],
    packaging: "500 adet/paket",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "sarf-petri",
    slug: "steril-petri-kutusu",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Steril Petri Kutusu - 90x15 mm (Havalandırmalı)",
    description: "Mikrobiyolojik kültür ve ekim çalışmaları için şeffaf optik kalitede petri kutusu.",
    features: ["90x15 mm standart ölçü", "EO sterilize"],
    packaging: "500 adet/koli",
    image: "/images/products/petri kutusu.jpeg",
  },
  {
    id: "sarf-serolojik-1",
    slug: "serolojik-pipet-1ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Serolojik Pipet - 1 ml (Tekli Ambalaj, Steril)",
    description: "Hücre kültürü ve sıvı transferleri için dereceli steril serolojik pipet.",
    features: ["1 ml hacim", "Pyrogen içermez, tekli steril paket"],
    packaging: "100 adet/kutu",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "sarf-serolojik-2",
    slug: "serolojik-pipet-2ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Serolojik Pipet - 2 ml (Tekli Ambalaj, Steril)",
    description: "Hassas sıvı aktarımları için tekli paketlenmiş steril serolojik pipet.",
    features: ["2 ml hacim", "Negatif derecelendirme"],
    packaging: "100 adet/kutu",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "sarf-serolojik-5",
    slug: "serolojik-pipet-5ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Serolojik Pipet - 5 ml (Tekli Ambalaj, Steril)",
    description: "Yüksek şeffaflığa sahip laboratuvar tipi steril serolojik pipet.",
    features: ["5 ml hacim", "Steril"],
    packaging: "100 adet/kutu",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "sarf-serolojik-10",
    slug: "serolojik-pipet-10ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Serolojik Pipet - 10 ml (Tekli Ambalaj, Steril)",
    description: "Genel laboratuvar sıvı dolum ve transfer işlemleri için ideal.",
    features: ["10 ml hacim", "Tekli peel-pack ambalaj"],
    packaging: "100 adet/kutu",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "sarf-serolojik-25",
    slug: "serolojik-pipet-25ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Serolojik Pipet - 25 ml (Tekli Ambalaj, Steril)",
    description: "Büyük hacimli hücre kültürü besiyeri aktarımları için steril pipet.",
    features: ["25 ml hacim", "Yüksek doğruluk oranı"],
    packaging: "50 adet/kutu",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "sarf-serolojik-50",
    slug: "serolojik-pipet-50ml",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Serolojik Pipet - 50 ml (Tekli Ambalaj, Steril)",
    description: "Geniş hacimli sıvılar için özel tasarlanmış tekli ambalajlı steril pipet.",
    features: ["50 ml hacim", "Steril"],
    packaging: "30 adet/kutu",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "sarf-deep-well",
    slug: "deep-well-plate-96",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Deep Well Plate (Derin Kuyulu Plaka) - 96 kuyucuklu, 2.2 ml",
    description: "Yüksek verimli numune saklama ve ekstraksiyon süreçleri için V-dipi derin kuyu pleyti.",
    features: ["96 kuyucuk", "2.2 ml hacim", "V-dipi taban"],
    packaging: "5 adet/paket",
    image: "/images/products/96- PCR Plate- şeffaf.jpeg",
  },
  {
    id: "sarf-pcr-plate",
    slug: "pcr-plate-96",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "PCR Plate (PCR Pleyti) - 96 kuyucuklu (Eteksiz / Etekli)",
    description: "Thermal sikler cihazları ile tam uyumlu yüksek ısı transferli 96'lı pleyt.",
    features: ["96 kuyucuk", "İnce duvarlı optik yapı"],
    packaging: "10 adet/paket",
    image: "/images/products/96- PCR Plate- şeffaf.jpeg",
  },
  {
    id: "sarf-lam-lamel",
    slug: "lam-ve-lamel-seti",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Lam ve Lamel Seti (Mikroskop için temiz kesim cam)",
    description: "Işık mikroskopisi çalışmalarında preparat hazırlamak için yüksek kaliteli cam set.",
    features: ["Standart mikroskop ölçüleri", "Temiz kenar kesim"],
    packaging: "50'li lam / 100'lü lamel kutu",
    image: "/images/products/beher.jpeg",
  },
  // Cam Malzemeler (Sarf Malzemeleri Altında)
  {
    slug: "borosilikat-cam-beher-50ml",
    id: "cam-beher-50",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Beher (Alçak Form, Dereceli) - 50 ml",
    description: "Isıya ve kimyasallara dayanıklı borosilikat 3.3 cam laboratuvar beheri.",
    features: ["50 ml hacim", "Yüksek ısı şoku direnci"],
    packaging: "Tekli kutu",
    image: "/images/products/beher.jpeg",
  },
  {
    slug: "borosilikat-cam-beher-100ml",
    id: "cam-beher-100",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Beher (Alçak Form, Dereceli) - 100 ml",
    description: "Dereceli alçak form borosilikat cam beher.",
    features: ["100 ml hacim", "Net hacim çizgileri"],
    packaging: "Tekli kutu",
    image: "/images/products/beher.jpeg",
  },
  {
    slug: "borosilikat-cam-beher-250ml",
    id: "cam-beher-250",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Beher (Alçak Form, Dereceli) - 250 ml",
    description: "Rutin laboratuvar ısıtma ve karıştırma işlemleri için cam beher.",
    features: ["250 ml hacim", "Damlatmasız ağızlık"],
    packaging: "Tekli kutu",
    image: "/images/products/beher.jpeg",
  },
  {
    slug: "borosilikat-cam-beher-500ml",
    id: "cam-beher-500",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Beher (Alçak Form, Dereceli) - 500 ml",
    description: "Orta hacimli çözelti hazırlama için borosilikat cam kap.",
    features: ["500 ml hacim", "Isıya dayanıklı"],
    packaging: "Tekli kutu",
    image: "/images/products/beher.jpeg",
  },
  {
    slug: "borosilikat-cam-beher-1000ml",
    id: "cam-beher-1000",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Beher (Alçak Form, Dereceli) - 1000 ml",
    description: "Büyük hacimli sıvı yönetimi için 1 litrelik cam beher.",
    features: ["1000 ml hacim", "Dereceli"],
    packaging: "Tekli kutu",
    image: "/images/products/beher.jpeg",
  },
  {
    slug: "borosilikat-cam-beher-2000ml",
    id: "cam-beher-2000",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Beher (Alçak Form, Dereceli) - 2000 ml",
    description: "Endüstriyel ve büyük ölçekli laboratuvar hazırlıkları için cam beher.",
    features: ["2000 ml hacim", "Borosilikat 3.3"],
    packaging: "Tekli kutu",
    image: "/images/products/beher.jpeg",
  },
  {
    slug: "borosilikat-cam-erlenmayer-100ml",
    id: "cam-erlen-100",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Erlenmayer (Dar Boyunlu) - 100 ml",
    description: "Titrasyon ve kültür hazırlama süreçleri için dar boyunlu konik cam erlen.",
    features: ["100 ml hacim", "Sıçramayı önleyen konik yapı"],
    packaging: "Tekli kutu",
    image: "/images/products/erlen.jpeg",
  },
  {
    slug: "borosilikat-cam-erlenmayer-250ml",
    id: "cam-erlen-250",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Erlenmayer (Dar Boyunlu) - 250 ml",
    description: "Mikrobiyolojik ve kimyasal reaksiyonlar için standart erlenmayer.",
    features: ["250 ml hacim", "Borosilikat cam"],
    packaging: "Tekli kutu",
    image: "/images/products/erlen.jpeg",
  },
  {
    slug: "borosilikat-cam-erlenmayer-500ml",
    id: "cam-erlen-500",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Erlenmayer (Dar Boyunlu) - 500 ml",
    description: "Orta boy çözelti hazırlama ve çalkalama işlemleri için cam erlen.",
    features: ["500 ml hacim", "Net dereceler"],
    packaging: "Tekli kutu",
    image: "/images/products/erlen.jpeg",
  },
  {
    slug: "borosilikat-cam-erlenmayer-1000ml",
    id: "cam-erlen-1000",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Erlenmayer (Dar Boyunlu) - 1000 ml",
    description: "Geniş hacimli solüsyon saklama ve kimyasal işlemler için erlen.",
    features: ["1000 ml hacim", "Isıya dayanıklı"],
    packaging: "Tekli kutu",
    image: "/images/products/erlen.jpeg",
  },
  {
    slug: "borosilikat-cam-balon-joje-100ml",
    id: "cam-balon-100",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Balon Joje (Tek Çizgili, Kalibre) - 100 ml",
    description: "Hassas konsantrasyonda çözelti hazırlamak için kalibre edilmiş ölçü balon jojesi.",
    features: ["100 ml hacim", "A sınıfı kalibrasyon hassasiyeti"],
    packaging: "Tekli kutu",
    image: "/images/products/balon joje.jpeg",
  },
  {
    slug: "borosilikat-cam-balon-joje-250ml",
    id: "cam-balon-250",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Balon Joje (Tek Çizgili, Kalibre) - 250 ml",
    description: "Analitik kimyada standart çözelti hazırlamak için tek çizgili balon joje.",
    features: ["250 ml hacim", "Plastik tıpalı sızdırmaz boyun"],
    packaging: "Tekli kutu",
    image: "/images/products/balon joje.jpeg",
  },
  {
    slug: "borosilikat-cam-balon-joje-500ml",
    id: "cam-balon-500",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Balon Joje (Tek Çizgili, Kalibre) - 500 ml",
    description: "Yüksek hassasiyetli sıvı hacmi ayarlama ve saklama balonu.",
    features: ["500 ml hacim", "Kalibre edilmiş cam"],
    packaging: "Tekli kutu",
    image: "/images/products/balon joje.jpeg",
  },
  {
    slug: "borosilikat-cam-balon-joje-1000ml",
    id: "cam-balon-1000",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Borosilikat Cam Balon Joje (Tek Çizgili, Kalibre) - 1000 ml",
    description: "1 litrelik hacim ayarlı analitik laboratuvar balon jojesi.",
    features: ["1000 ml hacim", "Borosilikat cam"],
    packaging: "Tekli kutu",
    image: "/images/products/balon joje.jpeg",
  },
  {
    slug: "reaktif-sisesi-250ml",
    id: "cam-reaktif-250",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Reaktif Şişesi (Vidalı Kapaklı, Amber / Şeffaf Cam) - 250 ml",
    description: "Kimyasalları güvenle saklamak için sızdırmaz kapaklı cam şişe.",
    features: ["250 ml hacim", "Amber veya şeffaf seçenek"],
    packaging: "Tekli kutu",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    slug: "reaktif-sisesi-500ml",
    id: "cam-reaktif-500",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Reaktif Şişesi (Vidalı Kapaklı, Amber / Şeffaf Cam) - 500 ml",
    description: "Işığa duyarlı veya standart reaktifler için vidalı kapaklı reaktif şişesi.",
    features: ["500 ml hacim", "Sızdırmaz halkalı kapak"],
    packaging: "Tekli kutu",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    slug: "reaktif-sisesi-1000ml",
    id: "cam-reaktif-1000",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Reaktif Şişesi (Vidalı Kapaklı, Amber / Şeffaf Cam) - 1000 ml",
    description: "1 litrelik geniş kapasiteli borosilikat cam reaktif saklama şişesi.",
    features: ["1000 ml hacim", "Dayanıklı cam yapı"],
    packaging: "Tekli kutu",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    slug: "dereceli-silindir-mezur",
    id: "cam-mezur",
    categorySlug: "laboratuvar-sarf-malzemeleri",
    categoryName: "Laboratuvar Sarf Malzemeleri",
    name: "Dereceli Silindir (Mezur) - 10 ml, 50 ml, 100 ml, 500 ml, 1000 ml",
    description: "Sıvı hacimlerini kademeli olarak ölçmek için altıgen tabanlı dereceli silindir.",
    features: ["Çeşitli hacim seçenekleri (10ml - 1000ml)", "Net ölçü çizgileri"],
    packaging: "Tekli kutu",
    image: "/images/products/erlen.jpeg",
  },

  // --- 2. PCR KİTLERİ VE MOLEKÜLER BİYOLOJİ ---
  {
    id: "pcr-taq-mix",
    slug: "2x-taq-dna-polymerase-master-mix",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "2X Taq DNA Polymerase Master Mix",
    description: "Rutin PCR ve genotipleme çalışmaları için optimize edilmiş hazır master mix çözeltisi.",
    features: ["Taq Polimeraz ve dNTP içerir", "Yüksek amplifikasyon verimliliği"],
    packaging: "500 reaksiyon",
    image: "/images/products/96- PCR Plate- şeffaf.jpeg",
  },
  {
    id: "pcr-qpcr-mix",
    slug: "qpcr-sybr-green-master-mix",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "Real-Time PCR (qPCR) SYBR Green Master Mix",
    description: "Gen ifadesi analizi ve kantitatif PCR uygulamaları için yüksek duyarlılıklı floresan master mix.",
    features: ["Yüksek hassasiyet", "Tüm real-time cihazlarla uyumlu"],
    packaging: "2 ml (200 reaksiyon)",
    image: "/images/products/PCR Tüpü 0,2 ml.jpeg",
  },
  {
    id: "pcr-gdn-kiti",
    slug: "genomik-dna-ekstraksiyon-kiti",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "Genomik DNA Ekstraksiyon Kiti (Kolon / Manyetik Boncuk Bazlı)",
    description: "Çeşitli biyolojik örneklerden yüksek verim ve saflıkta gDNA izolasyon kiti.",
    features: ["Hızlı protokol", "Yüksek DNA saflığı"],
    packaging: "50 prep / 250 prep",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "pcr-viral-rna",
    slug: "viral-rna-dna-izolasyon-kiti",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "Viral RNA / DNA İzolasyon Kiti",
    description: "Sıvı biyolojik örneklerden viral nükleik asit eldesi için optimize edilmiş kit.",
    features: ["Kritik patojen tespiti için yüksek geri kazanım"],
    packaging: "50 prep",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "pcr-miniprep",
    slug: "plasmid-dna-miniprep-kiti",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "Plasmid DNA Miniprep Kiti",
    description: "Bakteriyel kültürlerden saf plasmid DNA saflaştırma kiti.",
    features: ["Spin kolon teknolojisi", "Hızlı ve güvenilir"],
    packaging: "50 prep",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "pcr-gel-ekstraksiyon",
    slug: "jel-ekstraksiyon-ve-pcr-temizleme-kiti",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "Jel Ekstraksiyon ve PCR Temizleme Kiti",
    description: "Agaroz jelden DNA bantlarının kesilip saflaştırılması ve PCR ürünlerinin temizlenmesi için.",
    features: ["Yüksek geri kazanım verimi"],
    packaging: "50 prep",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "pcr-elisa-kit",
    slug: "sandwich-elisa-test-kitleri",
    categorySlug: "pcr-kitleri",
    categoryName: "PCR Kitleri",
    name: "Sandwich ELISA Test Kitleri (Çeşitli biyolojik belirteçler için)",
    description: "Hassas immünolojik tayinler ve protein konsantrasyon ölçümleri için ELISA kitleri.",
    features: ["Yüksek spesifite ve duyarlılık"],
    packaging: "96 test / plaka",
    image: "/images/products/96- PCR Plate- şeffaf.jpeg",
  },

  // --- 3. KİMYASALLAR VE REAKTİFLER (15 Adet Genişletilmiş Liste) ---
  {
    id: "kim-1",
    name: "Agaroz (Molecular Biology Grade)",
    slug: "agaroz-molecular-biology-grade",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Nükleik asitlerin elektroforezinde yüksek çözünürlük sağlayan saf moleküler biyoloji sınıfı agaroz.",
    features: ["Düşük elektroforez arka planı", "Yüksek jel mukavemeti", "Hızlı donma özelliği"],
    packaging: "100 g",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "kim-2",
    name: "TE Buffer (1X, Sterile)",
    slug: "te-buffer-1x-sterile",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "DNA ve RNA saklama ile çözme işlemlerinde kullanılan steril ve nükleaz içermeyen tampon çözelti.",
    features: ["Steril ve kullanıma hazır", "pH 8.0 stabilizasyonu", "Nükleaz içermez"],
    packaging: "500 ml",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-3",
    name: "Etanol (Absolute, %99.9 Analitik Saflık)",
    slug: "etanol-absolute-99-9",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Nükleik asit çöktürme ve laboratuvar yüzey/cihaz temizliği için yüksek saflıkta etanol.",
    features: ["%99.9 saf", "Düşük kalıntı oranı"],
    packaging: "2.5 L",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-4",
    name: "İzopropil Alkol (IPA, Molecular Biology Grade)",
    slug: "izopropil-alkol-molecular-grade",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "DNA ve RNA ekstraksiyon protokollerinde çökeltme amacıyla kullanılan saf izopropanol.",
    features: ["Nükleaz içermez", "Yüksek saflık"],
    packaging: "1 L",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-5",
    name: "PBS Tampon Çözeltisi (1X, Steril)",
    slug: "pbs-tampon-cozeltisi-1x",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Hücre yıkama, sulandırma ve biyolojik deneylerde kullanılan fizyolojik fosfat tamponlu tuz çözeltisi.",
    features: ["pH 7.4", "Steril ve süzülmüş"],
    packaging: "1 L",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-6",
    name: "Tris-Base (Molecular Biology Grade)",
    slug: "tris-base-molecular-grade",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Tampon çözelti hazırlamada kullanılan yüksek saflıkta Tris(hidroksimetil)aminometan tozu.",
    features: ["%99.9 saflık", "Ağır metal içermez"],
    packaging: "500 g",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "kim-7",
    name: "EDTA Disodyum Tuzu (2Na EDTA)",
    slug: "edta-disodyum-tuzu",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Nükleazları inaktive etmek için şelatlayıcı ajan olarak kullanılan analitik saflıkta EDTA.",
    features: ["Metal iyonlarını bağlama özelliği", "Kolay çözünür"],
    packaging: "250 g",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "kim-8",
    name: "SDS Çözeltisi (%10, Ultra Saf)",
    slug: "sds-cozeltisi-yuzde-10",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Protein denatürasyonu ve elektroforez süreçleri için sodyum dodesil sülfat çözeltisi.",
    features: ["Elektroforez kalitesinde", "Kullanıma hazır sıvı form"],
    packaging: "500 ml",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-9",
    name: "Proteinaz K (Enzim, Liyofilize)",
    slug: "proteinaz-k-toz",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Ekstraksiyon sırasında proteinleri parçalamak için kullanılan geniş spektrumlu endopeptidaz enzim.",
    features: ["Yüksek enzim aktivitesi", "Stabil liyofilize form"],
    packaging: "100 mg / 1 g",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  },
  {
    id: "kim-10",
    name: "LB Broth (Miller - Mikrobiyolojik Besiyeri)",
    slug: "lb-broth-miller",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Bakteri (E. coli) kültivasyon ve çoğaltma işlemlerinde kullanılan standart Luria-Bertani besiyeri tozu.",
    features: ["Kolay hazırlanan formül", "Bakteri gelişimine uygun besin dengesi"],
    packaging: "500 g",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "kim-11",
    name: "Bakteriyolojik Agar Tozu",
    slug: "bakteriyolojik-agar-tozu",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Petri kutusu ve katı besiyeri hazırlamak için yüksek mukavemetli saf agar tozu.",
    features: ["Optimum jelleşme sıcaklığı", "Berrak jel görünümü"],
    packaging: "500 g",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "kim-12",
    name: "Gliserol (%99 Saf, Anhydrous)",
    slug: "gliserol-99-saf",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Enzim saklama koşullarında (stok solüsyonlar) kriyoprotektan olarak kullanılan saf gliserin.",
    features: ["%99 anhidröz", "Yüksek saflık"],
    packaging: "1 L",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-13",
    name: "Hidroklorik Asit (HCl, %37 Analitik)",
    slug: "hidroklorik-asit-37",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "pH ayarlama ve asit baz titrasyonları için analitik saflıkta konsantre HCl.",
    features: ["Analiz sertifikalı", "Yüksek konsantrasyon"],
    packaging: "2.5 L",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "kim-14",
    name: "Sodyum Hidroksit (NaOH Pelet)",
    slug: "sodyum-hidroksit-pelet",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Tampon hazırlığı ve bazik pH ayarlamaları için yüksek saflıkta NaOH peletleri.",
    features: ["Kolay çözünür form", "Analitik saflık"],
    packaging: "1 kg",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "kim-15",
    name: "Aseton (ACS Reagent Grade)",
    slug: "aceton-acs-grade",
    categorySlug: "kimyasallar-ve-reaktifler",
    categoryName: "Kimyasallar ve Reaktifler",
    description: "Laboratuvar cam malzemelerini kurutma ve temizleme süreçlerinde kullanılan saf aseton.",
    features: ["Hızlı uçucu", "Düşük kalıntı"],
    packaging: "2.5 L",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },

  // --- 4. LABORATUVAR CİHAZLARI (Markasız) ---
  {
    id: "dev-hipette",
    slug: "mekanik-pipet",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Mekanik Pipet (Tek ve Çok Kanallı Modeller)",
    description: "Tam otoklavlanabilir, ultra hafif ve ergonomik tasarımlı yeni nesil mekanik pipet serisi.",
    features: ["0.1µl - 10ml geniş hacim seçenekleri", "4 haneli net hacim ekranı", "Tamamen otoklavlanabilir"],
    packaging: "1 adet cihaz + kalibrasyon sertifikası",
    image: "/images/products/serolojik pipet.jpeg",
    whatIsIt: "Hassas hacimlerde sıvı transferi yapmak için kullanılan manuel ayarlanabilir mikropipet.",
    whyUsed: "Yüksek tekrarlanabilirlik ve uzun ömürlü ergonomik kullanım sağlar.",
  },
  {
    id: "dev-mipette",
    slug: "lts-pipet",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Yeni Nesil Otoklavlanabilir Pipet",
    description: "Düşük uç atma kuvveti ve ergonomik yapısıyla öne çıkan otoklavlanabilir pipet.",
    features: ["LTS uyumlu uç opsiyonu", "Hafif ve yorulmayan gövde"],
    packaging: "1 adet cihaz",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "dev-micropette-plus",
    slug: "micropette-plus",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Tam Otoklavlanabilir Mekanik Pipet",
    description: "121°C sıcaklıkta tamamen otoklavlanabilen dayanıklı mekanik pipet serisi.",
    features: ["Sabit ve ayarlanabilir hacim formatları", "Kolay kalibrasyon"],
    packaging: "1 adet cihaz",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "dev-toppette",
    slug: "ergonomik-pipet",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Ergonomik Ayarlanabilir/Sabit Hacimli Pipet",
    description: "Günlük laboratuvar rutinleri için ekonomik, hafif ve hassas mekanik pipet.",
    features: ["0.1µL - 20mL aralığı", "ISO 8655 standartlarına uygun"],
    packaging: "1 adet cihaz",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "dev-mini-top",
    slug: "mini-toppette",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Sabit Hacimli Kompakt Pipet",
    description: "IVD kitleri ve hızlı testler için özel tasarlanmış sabit hacimli mini pipet.",
    features: ["Kompakt 13cm boy", "Tek elle kolay kullanım"],
    packaging: "1 adet cihaz",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "dev-epette",
    slug: "electronic-pipette",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Elektronik Pipet (OLED Dokunmatik Ekranlı)",
    description: "Akıllı dokunmatik ekran, yüksek hassasiyetli motor ve çoklu çalışma modlarına sahip akıllı elektronik pipet.",
    features: ["2.1 inç OLED HD dokunmatik ekran", "Tek tuşla uç atma", "Çoklu çalışma modları"],
    packaging: "1 adet cihaz + şarj standı",
    image: "/images/products/dlab-epette.jpg",
  },
  {
    id: "dev-dpette",
    slug: "dpette-plus-electronic",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Çok Fonksiyonlu Elektronik Pipet",
    description: "Motorize sürüş mekanizmasıyla çalışan, dijital kontrollü çok fonksiyonlu sıvı aktarım cihazı.",
    features: ["Pipetleme, karıştırma ve dilüsyon modları", "360° döner başlık"],
    packaging: "1 adet cihaz",
    image: "/images/products/dlab-epette.jpg",
  },
  {
    id: "dev-levo-plus",
    slug: "levo-plus-pipette-filler",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Serolojik Pipet Kontrol Cihazları",
    description: "0.1-100ml cam veya plastik serolojik pipetler ile uyumlu hızlı ve ergonomik doldurucu.",
    features: ["6 kademeli hız ayarı", "LCD pil göstergesi", "Güçlü sessiz motor"],
    packaging: "1 adet cihaz + şarj standı",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "dev-stepmate",
    slug: "stepmate-stepper",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Tekrarlacıklı Dispenser (Stepper)",
    description: "Seri ve tekrarlamalı dağıtım işlemleri için pozitif deplasmanlı dispenser.",
    features: ["0.5ml - 50ml arası geniş dağıtım", "Tek dolumla 48 adıma kadar seri atım"],
    packaging: "1 adet cihaz",
    image: "/images/products/serolojik pipet.jpeg",
  },
  {
    id: "dev-dispensmate",
    slug: "dispensmate-bottle-top-dispenser",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Şişe Üstü Dispenser",
    description: "Şişe üzerinden güvenli, asit ve bazlara dayanıklı yüksek hassasiyetli dispenser.",
    features: ["Mükemmel kimyasal direnç", "121°C'de otoklavlanabilir"],
    packaging: "1 adet cihaz + adaptör seti",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  {
    id: "dev-dtrite",
    slug: "dtrite-electronic-titrator",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Elektronik Titratör (Büret)",
    description: "Analitik kimya titrasyon işlemlerinde geleneksel büretin yerini alan motorize akıllı titratör.",
    features: ["Manyetik karıştırıcı entegre opsiyonu", "LCD ekran ve hassas motor"],
    packaging: "1 adet cihaz",
    image: "/images/products/Reaktif şişesi- cam 500 ml.jpeg",
  },
  // Santrifüj Sistemleri
  {
    id: "dev-d1008",
    slug: "d1008-palm-micro-centrifuge",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Palm Micro Centrifuge (Mini Santrifüj)",
    description: "Hızlı spin-down işlemleri ve mikrofiltrasyon için kompakt masaüstü mini santrifüj.",
    features: ["7000 rpm hız", "Sessiz ve titreşimsiz çalışma"],
    packaging: "1 adet cihaz",
    image: "/images/products/falkon tüp 15ml- steril olmayan.jpeg",
  },
  {
    id: "dev-d2012",
    slug: "d2012-plus-micro-centrifuge",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Yüksek Hız Mikro Santrifüj (15.000 rpm)",
    description: "15.000 rpm hıza sahip, fırçasız DC motorlu, yüksek performanslı mikro santrifüj.",
    features: ["15.100 xg maksimum RCF", "Otomatik kapak kilidi"],
    packaging: "1 adet cihaz + rotor",
    image: "/images/products/falkon tüp 15ml- steril olmayan.jpeg",
  },
  {
    id: "dev-d1524r",
    slug: "d1524r-refrigerated-centrifuge",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Yüksek Hız Soğutmalı Mikro Santrifüj",
    description: "-20°C ila +40°C sıcaklık aralığına sahip hassas soğutmalı mikro santrifüj.",
    features: ["Hızlı precooling (7 dakikada 4°C)", "3 kat sızdırmaz bioseal rotor"],
    packaging: "1 adet cihaz",
    image: "/images/products/falkon tüp 15ml- steril olmayan.jpeg",
  },
  {
    id: "dev-d3024",
    slug: "d3024-high-speed-centrifuge",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Yüksek Hız Üç Kat Sızdırmaz Mikro Santrifüj",
    description: "Askeri-endüstriyel sınıf alüminyum alaşımlı bioseal rotorlu yüksek hız santrifüjü.",
    features: ["21.380 xg max RCF", "Çift soğutma hava sirkülasyonu"],
    packaging: "1 adet cihaz",
    image: "/images/products/falkon tüp 15ml- steril olmayan.jpeg",
  },
  {
    id: "dev-dg1616",
    slug: "dg1616-high-speed-centrifuge",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Yüksek Hız / Soğutmalı Büyük Kapasiteli Santrifüj",
    description: "4x400ml kapasiteye kadar çıkabilen dokunmatik ekranlı yüksek performanslı santrifüj.",
    features: ["16.000 rpm maksimum hız", "Akıllı balans ve dengesizlik algılama"],
    packaging: "1 adet cihaz",
    image: "/images/products/falkon tüp 15ml- steril olmayan.jpeg",
  },
  // Termal ve PCR Sistemleri
  {
    id: "dev-drybath",
    slug: "dijital-kuru-blok-isitici",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Dijital Kuru Blok Isıtıcılar (Dry Bath)",
    description: "Hassas sıcaklık kontrolü sağlayan değiştirilebilir bloklu laboratuvar ısıtıcısı.",
    features: ["150°C'ye varan ısıtma kapasitesi", "Gerçek zamanlı sıcaklık izleme"],
    packaging: "1 adet cihaz",
    image: "/images/products/erlen.jpeg",
  },
  {
    id: "dev-thermomix",
    slug: "thermomix-hcm100-pro",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Thermo Mix (Isıtma, Soğutma ve Karıştırma)",
    description: "Isıtma, soğutma ve titrek karıştırma fonksiyonlarını tek cihazda birleştiren sistem.",
    features: ["200-1500 rpm karıştırma hızı", "-5°C ila 110°C sıcaklık aralığı"],
    packaging: "1 adet cihaz",
    image: "/images/products/erlen.jpeg",
  },
  {
    id: "dev-tc1000",
    slug: "tc1000-gradient-pcr-cihazi",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Gradient PCR Cihazı (Termal Sikler)",
    description: "Gelişmiş Peltier teknolojisi ve dokunmatik ekranlı genetik amplifikasyon cihazı.",
    features: ["96 kuyucuklu blok", "5°C/sn maksimum sıcaklık değişim hızı"],
    packaging: "1 adet cihaz",
    image: "/images/products/96- PCR Plate- şeffaf.jpeg",
  },
  // Karıştırma ve Isıtma Cihazları
  {
    id: "dev-ms-h-pro",
    slug: "ms-h-pro-manyetik-karistirici",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "LCD Dijital Isıtıcılı Manyetik Karıştırıcı",
    description: "Seramik kaplı alüminyum tabla, 340°C ısıtma ve fırçasız DC motorlu karıştırıcı.",
    features: ["20 Litreye kadar karıştırma", "PT1000 harici prob desteği", "HOT uyarı lambası"],
    packaging: "1 adet cihaz + PT1000 prob",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "dev-multichannel-stirrer",
    slug: "cok-kanalli-manyetik-karistirici",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Çok Kanallı (4 ve 6 lı) Manyetik Karıştırıcı",
    description: "Paralel deneyler için bağımsız kontrollü 4 ve 6 istasyonlu ısıtıcılı karıştırıcı.",
    features: ["Her kanal için ayrı hız ve sıcaklık kontrolü", "Yer tasarrufu sağlayan tasarım"],
    packaging: "1 adet cihaz",
    image: "/images/products/beher.jpeg",
  },
  {
    id: "dev-overhead",
    slug: "ustten-karistirici-overhead-stirrer",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Üstten Karıştırıcılar (Overhead Stirrers)",
    description: "Orta ve yüksek viskoziteli sıvılar için güçlü torka sahip motorlu üstten karıştırıcı.",
    features: ["50-2200 rpm hız aralığı", "Viskozite değişmelerinde sabit hız koruması"],
    packaging: "1 adet cihaz + karıştırma mili",
    image: "/images/products/balon joje.jpeg",
  },
  // Evaporatör ve Vakum
  {
    id: "dev-re100",
    slug: "re100-pro-rotary-evaporator",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Dijital Rotatif Evaporatör Sistemleri",
    description: "Hassas vakumlu distilasyon, solvent uzaklaştırma ve konsantrasyon için sistem.",
    features: ["Motorlu otomatik kaldırma", "5L dijital ısıtma banyosu", "Yüksek verimli kondenser"],
    packaging: "1 adet cihaz + cam set",
    image: "/images/products/balon joje.jpeg",
  },
  {
    id: "dev-safevac",
    slug: "safevac-vakumlu-atik-sistem",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Vakumlu Atık Sıvı Aspinasyon Sistemleri",
    description: "Hücre kültürü supernatantları ve biyolojik sıvı atıklarını güvenle çeken vakum sistemi.",
    features: ["Seviye sensörlü taşma koruması", "Otokotlanabilir atık şişesi"],
    packaging: "1 adet cihaz + şişe seti",
    image: "/images/products/erlen.jpeg",
  },
  // Vortex ve Çalkalayıcılar
  {
    id: "dev-vortex",
    slug: "mx-pro-mx-s-vortex-karistirici",
    categorySlug: "laboratuvar-cihazlari",
    categoryName: "Laboratuvar Cihazları",
    name: "Dijital Vortex Karıştırıcı",
    description: "Tüpleri otomatik algılayan kızılötesi sensörlü veya dokunmatik modlu güçlü vortex.",
    features: ["0-3000 rpm değişken hız", "Fırçasız sessiz DC motor"],
    packaging: "1 adet cihaz",
    image: "/images/products/ependorf tüp 1,5 ml.jpeg",
  }
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductCategoryBySlug(slug: string) {
  return productCategories.find((c) => c.slug === slug);
}

export function getAllProducts(): Product[] {
  return products;
}